### ISSUE TITLE
How to Display image in another layout instead of a new window?

### ISSUE THREAD

**Issue by bxh7425014** [hao-lee/Graphvizer#2]
How to display image in another layout instead of a new window, in sublime text 3.

**Comment by hao-lee** [comment]
Hi, this feature haven't been implemented yet because I don't know if it is necessary. I think a separated window is more flexible than a layout. I want to know why you want to display the image in another layout instead of a window.

**Comment by hao-lee** [comment]
This feature has been added. See the [documentation](https://github.com/hao-lee/Graphvizer#show-the-image-in-a-separated-layout) for details. Thanks for your advice.

**Comment by hao-lee** [comment]
Oh, I introduced a new bug in these commits, so I will release the new version a day later. :smiley:

**Comment by PaulPoinet** [comment]
Hi, about display I have a remark/question. 
When the graph becomes too big, the window or the layout do not adapt and its impossible to zoom. 
It seems that this problem is inherent to Sublime Text though: https://stackoverflow.com/questions/41368910/sublime-text-3-zoom-image-in-internal-viewer
Any thought on this?

**Comment by hao-lee** [comment]
@PaulPoinet Hi, for now, Sublime doesn't support image zooming. I think this is because its developers are mainly focusing on text editing functionality, although I also think image zooming is a very useful feature. Besides, I think using scrollbars to move image is very inconvenient and Sublime should let me drag the image directly. It should also restore the image position after the image refresh automatically. I plan to write a simple viewer using Python and I'm currently thinking a suitable way to implement it.

**Comment by PaulPoinet** [comment]
Ok, thank you for the insight!
